### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by imcompiling** [drallgood/audiobookshelf-hardcover-sync#19]
I am now seeing different sync behavior that is still not desired. One specific book is getting marked as read about once a day even though it has been finished weeks ago without any updates.

Additionally, the books that I am currently reading are not receiving any updates at all. I went through the logs and one of them wasn't appearing in the scan at all for some reason, and the other one did but was initially ignored because I had just started it and it was a very small complete %. Now I have read more and the complete % is greater than the threshold, but no updates have appeared. I haven't been back to look at the logs since though.

Any ideas on what is going on? Do I need to get you any logs to help troubleshoot this?

**Comment by drallgood** [comment]
Oh I see that one too.. still trying to figure out why that specific book is different than any others @imcompiling It's super strange. I have a suspicion that it's actually a HC bug, but haven't had time to nail it down yet.

As for the book you're reading. Haven't seen that one. All my books show up correctly.
Can you share the relevant logs (ideally in debug mode) for that book?

**Comment by drallgood** [comment]
@imcompiling can you set the LOG_LEVEL to debug please? Should give you tons more info

**Comment by drallgood** [comment]
nvm.. I see it's already on debug. 

It should tell you why it wasn't synced. Usually something about progress values

**Comment by imcompiling** [comment]
For clarification: `The Devils` is not a reread (and is not obtaining any auto updates), but the book that was correctly marked as read when finished, though no progress updates, and the new book without an automatic start and no progress updates are both rereads.

**Comment by imcompiling** [comment]
Hmm yes that could definitely have been a problem. I did not have matching ASIN/ISBM for `The Devils` nor `Iron Prince` (book just started). I fixed that, so we will see if that results in success. That said, previous book (`Not Till We Are Lost`) was correct, but that one could be due to rereads.

Looking at all those ids gave raise to a different issue unrelated to this script or maybe even HC... `Iron Prince` has one ASIN in the audible url but HC has a different one. An ASIN lookup tool found the book with the one that HC has, but ABS lookup using audible.com could only find it with the one in the audible url. Confusing all around.

**Comment by drallgood** [comment]
Any chance the books tha get updated frequently are actually books where you have read more than one edition for the same book?

Turns out that was the issue in my case. I was treating the edition field in user_book as a filter but really, it's irrelevant. Can only have one entry per book+user 
Makes sense.. but I did it wrong :D

**Comment by imcompiling** [comment]
Nope, it's a book that I've only read once and it's not even creating a new read entry. I also only have marked 1 version as owned, and only have the audiobook.

**Comment by drallgood** [comment]
that might be a different topic.. I meant the thing you original mentioned:
"I am now seeing different sync behavior that is still not desired. One specific book is getting marked as read about once a day even though it has been finished weeks ago without any updates."

For me this happens for books with multiple editions

**Comment by imcompiling** [comment]
Hmm, it has a couple. I'll have to make sure that my abs info lines up with one that is on HC.
